language: ruby
cache: bundler
rvm:
  - 2.6
  - 2.4

before_script: bundle update
script: script/cibuild

notifications:
  email: false

env:
  - JEKYLL_VERSION=tip
  - JEKYLL_VERSION=3.7
  - JEKYLL_VERSION=2.0
